version: '3.8'

services:
  otel-collector:
    build: .
    container_name: welysn-otel-collector
    ports:
      - "4318:4318"  # OTLP HTTP receiver
    volumes:
      - ./collector-config.yaml:/etc/otelcol/config.yaml
    environment:
      BASIC_AUTH_HTPASSWD: ${BASIC_AUTH_HTPASSWD}